language: node_js
node_js: "6"

before_install:
  - npm install -g picanhajs
  - npm update
script: picanha grill
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: _build
